service:
  name: menuo
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  client:
    bucketName: serverless-client-menuo

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-finch

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:

  get-menu:
    handler: src/menu/handlers/get-menu.handler
    events:
      - http:
          path: menus/{restaurantId}
          method: get
          request:
            parameters:
              paths:
                restaurantId: true
