service:
  name: menuo
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  client:
    bucketName: menuo.me
    distributionFolder: client/build

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-finch

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:

  get-restaurant-menu:
    handler: src/restaurant/handlers/get-restaurant-menu.handler
    events:
      - http:
          path: restaurants/{restaurantId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                restaurantId: true

  get-restaurant-orders:
    handler: src/restaurant/handlers/get-restaurant-orders.handler
    events:
      - http:
          path: orders/{restaurantId}
          method: get 
          cors: true
          request:
            parameters:
              paths:
                restaurantId: true

  post-restaurant-orders:
    handler: src/restaurant/handlers/post-restaurant-orders.handler
    events:
      - http:
          path: orders/{restaurantId}
          method: post
          cors: true
          request:
            parameters:
              paths:
                restaurantId: true

  put-restaurant-orders:
    handler: src/restaurant/handlers/put-restaurant-orders.handler
    events:
      - http:
          path: orders/{restaurantId}
          method: put 
          cors: true
          request:
            parameters:
              paths:
                restaurantId: true

  logs:
    handler: src/logs/handlers/log.handler
    events:
      - cloudwatchLog: '/aws/lambda/menuo-dev-get-restaurant' # FIXME: hardcoded
