service:
  name: menuo
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  client:
    bucketName: menuo.me
    distributionFolder: ../client/build

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-finch

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:

  get-restaurant-menu:
    handler: src/restaurant/handlers/get-restaurant-menu.handler
    events:
      - http:
          path: restaurants/{restaurant}/dishes
          method: get
          cors: true
          request:
            parameters:
              paths:
                restaurant: true

  get-restaurant-orders:
    handler: src/restaurant/handlers/get-restaurant-orders.handler
    events:
      - http:
          path: restaurants/{restaurant}/orders
          method: get 
          cors: true
          request:
            parameters:
              paths:
                restaurant: true

  post-restaurant-orders:
    handler: src/restaurant/handlers/post-restaurant-orders.handler
    events:
      - http:
          path: restaurants/{restaurant}/orders
          method: post
          cors: true
          request:
            parameters:
              paths:
                restaurant: true

  delete-restaurant-order:
    handler: src/restaurant/handlers/delete-restaurant-order.handler
    events:
      - http:
          path: restaurants/{restaurant}/orders/{order}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                restaurant: true
                order: true

  put-restaurant-orders:
    handler: src/restaurant/handlers/put-restaurant-orders.handler
    events:
      - http:
          path: restaurants/{restaurant}/orders/{order}
          method: put 
          cors: true
          request:
            parameters:
              paths:
                restaurant: true
                order: true

  get-restaurant-table:
    handler: src/restaurant/handlers/get-restaurant-table.handler
    events:
      - http:
          path: restaurants/{restaurant}/tables/{table}
          method: get 
          cors: true
          request:
            parameters:
              paths:
                restaurant: true
                table: true

  logs:
    handler: src/logs/handlers/log.handler
    events:
      - cloudwatchLog: '/aws/lambda/menuo-dev-get-restaurant' # FIXME: hardcoded
